name: Show Terraform plan on PR
description: Show Terraform plan on PR

inputs:
  terraform_dir:
    description: The working directory, e.g. where the Terraform files are located.
    required: true
  service_account_key:
    description: Terraform Service Account private key to use with `gcloud`. If not specified, will be read from 'tf-pr-action-config.json'. If not set there either, Workload Identity Federation with project.config.json will be used, based on environment in `tf-pr-action-config.json`.
    required: false
    default: ""
  github_token:
    description: Token used when authenticating with GitHub. Defaults to `github.token`.
    required: false
    default: ${{ github.token }}
  secrets_json:
    description: JSON string containing secrets to pass to Terraform.
    required: false
    default: "{}"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}

    - name: Read Terraform PR config
      id: read-terraform-pr-config
      uses: svvsaga/github-actions-public/read-terraform-pr-config@v17.2.3
      with:
        cwd: ${{ inputs.terraform_dir }}
        secrets_json: ${{ inputs.secrets_json }}

    - name: Read Terraform dependencies
      id: read-terraform-dependencies
      uses: svvsaga/github-actions-public/read-terraform-dependencies@v17.2.3
      with:
        cwd: ${{ inputs.terraform_dir }}

    - name: Setup Google Cloud SDK
      uses: svvsaga/github-actions-public/setup-gcloud@v17.2.3
      with:
        app_root: ${{ inputs.terraform_dir }}
        environment: ${{ steps.read-terraform-pr-config.outputs.environment }}
        service_account_key: ${{ inputs.service_account_key || steps.read-terraform-pr-config.outputs.sa_secret_key }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ steps.read-terraform-dependencies.outputs.tf_version }}
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@d4de6a145d2e35e57ce5a5b856238ed3ada062b9
      with:
        terragrunt_version: ${{ steps.read-terraform-dependencies.outputs.tg_version }}

    - name: Terraform init dependencies
      uses: actions/github-script@v6
      env:
        DEPENDENCIES: ${{ steps.read-terraform-dependencies.outputs.tg_dependencies }}
        ENVIRONMENT: ${{ steps.read-terraform-pr-config.outputs.environment }}
        CWD: ${{ inputs.terraform_dir }}
      with:
        script: |
          const path = require('path')
          const fs = require('fs')
          const dependencies = process.env.DEPENDENCIES && JSON.parse(process.env.DEPENDENCIES);
          const environment = process.env.ENVIRONMENT;
          const cwd = process.env.CWD;
          const env = process.env;
          env.TF_INPUT = 'false'
          env.TF_VAR_ENV = environment
          if (dependencies && dependencies.length > 0) {
            const args = [
              'init',
              '-reconfigure'
            ]
            for (const dependency of dependencies) {
              console.log("cwd", cwd, "dependency", dependency)
              const resolved = path.resolve(cwd, dependency)
              console.log("resolved", resolved)
              const backendConfigFile = `environments/${environment}-backend-config.hcl`
              const dependencyArgs = args.slice()
              if (environment && fs.existsSync(path.resolve(resolved, backendConfigFile))) {
                dependencyArgs.push(`-backend-config=${backendConfigFile}`)
              }
              await exec.exec('terragrunt', dependencyArgs, {
                env,
                cwd: resolved,
                ignoreReturnCode: true
              });
            }
          }

    - name: Terraform init
      working-directory: ${{ inputs.terraform_dir }}
      id: init
      shell: bash
      env:
        TF_VAR_ENV: ${{ steps.read-terraform-pr-config.outputs.environment }}
        TF_INPUT: 'false'
      run: |
        if [ -n "$TF_VAR_ENV" ] && [ -f "environments/${TF_VAR_ENV}-backend-config.hcl" ]; then
          terragrunt init -backend-config="environments/${TF_VAR_ENV}-backend-config.hcl" && echo "INIT_OUTCOME=success" >> $GITHUB_ENV || echo "INIT_OUTCOME=failure" >> $GITHUB_ENV
        else
          terragrunt init && echo "INIT_OUTCOME=success" >> $GITHUB_ENV || echo "INIT_OUTCOME=failure" >> $GITHUB_ENV
        fi

    - name: Terraform format
      working-directory: ${{ inputs.terraform_dir }}
      id: fmt
      shell: bash
      env:
        TF_VAR_ENV: ${{ steps.read-terraform-pr-config.outputs.environment }}
      run: terragrunt fmt -check -diff -recursive && echo "FMT_OUTCOME=success" >> $GITHUB_ENV || echo "FMT_OUTCOME=failure" >> $GITHUB_ENV

    - name: Terraform plan
      working-directory: ${{ inputs.terraform_dir }}
      id: plan
      shell: bash
      env:
        TF_VAR_ENV: ${{ steps.read-terraform-pr-config.outputs.environment }}
        TF_VARS: ${{ steps.read-terraform-pr-config.outputs.tf_vars }}
        TF_INPUT: 'false'
      run: |
        if [ -n "$TF_VARS" ]; then
          echo "$TF_VARS" > extra.auto.tfvars.json
        fi
        if [ -n "$TF_VAR_ENV" ] & [ -f "environments/$TF_VAR_ENV.tfvars" ]; then
          terragrunt plan -no-color -var-file="environments/$TF_VAR_ENV.tfvars" -out="tf.plan"
        else
          terragrunt plan -no-color -out="tf.plan"
        fi
        # Maximum length of github comments is 65536 Unicode characters, so we cut the plan to 60000 chars if it is too long
        # See https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867
        PLAN=$(terragrunt show -no-color tf.plan)
        if [[ ${#PLAN} -gt 60000 ]] ; then
            PLAN="${PLAN::60000}"$'\n...\nPlan too long to be shown in full'
        fi
        echo 'PLAN<<EOF' >> $GITHUB_ENV
        echo "$PLAN" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV && echo "PLAN_OUTCOME=success" >> $GITHUB_ENV || echo "PLAN_OUTCOME=failure" >> $GITHUB_ENV

    - name: Show Terraform status
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          const plan = process.env.PLAN;
          const output = `
          <h1>${{ inputs.terraform_dir == '.' && 'root' || inputs.terraform_dir }}</h1>

          #### Terraform Format and Style 🖌\`${{ env.FMT_OUTCOME == 'success' && '✅' || env.FMT_OUTCOME == 'failure' && '❌' }}\`
          #### Terraform Initialization ⚙️\`${{ env.INIT_OUTCOME == 'success' && '✅' || env.INIT_OUTCOME == 'failure' && '❌' }}\`
          #### Terraform Plan 📖\`${{ env.PLAN_OUTCOME == 'success' && '✅' || env.PLAN_OUTCOME == 'failure' && '❌' }}\`


          <details><summary>Show Plan</summary>

          \`\`\`terraform\n${plan}\n\`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
