name: Find Terraform changes
description: Find changes in Terraform modules in a pull request or push. Requires checking out the code beforehand.
runs:
  using: node16
  main: ./index.js
inputs:
  token:
    description: GitHub token. Defaults to `github.token`.
    required: true
    default: ${{ github.token }}
  marker:
    description: A file that marks the root of a Terraform module. Defaults to `terragrunt.hcl`.
    required: true
    default: terragrunt.hcl
  ignore_modules:
    description: Comma-separated list of relative paths to ignore. Must include dot at start of relative path, e.g. `., ./system/alpha`.
    required: false
  ignore_modules_regex:
    description: Regex of modules to ignore, e.g. 'utils/.*'.
    required: false
  cwd:
    description: Relative path to use for searching and as root for `matrix.path` outputs. Defaults to repo root.
    required: true
    default: .
outputs:
  matrix:
    description: Matrix of terraform paths with changes in this PR/push. Use `matrix.path` for full path, `matrix.segments` for an array of each path segment, or `matrix.folder` for the single folder containing the module.
  has_results:
    description: Whether the matrix is empty or not; `true` if there are more than zero results, `false` otherwise.