name: Read Terraform PR-specific config
description: Finds Terraform settings to use when running PR actions.
runs:
  using: node20
  main: ./index.js
inputs:
  cwd:
    description: Relative path to use for searching and as root for `matrix.path` outputs. Defaults to repo root.
    required: true
    default: .
  secrets_json:
    description: JSON string containing secrets to use for Terraform.
    required: false
    default: "{}"
outputs:
  tf_vars:
    description: Terraform variables (as stringified JSON)
  sa_secret:
    description: Name of service account secret
  sa_secret_key:
    description: Service account secret key
  environment:
    description: Environment name to use when running Terraform PR actions
  workload_identity_project_id:
    description: Project ID for the workload identity federation authentication
  workload_identity_project_number:
    description: Project number for the workload identity federation authentication