name: Read project config
description: Finds project IDs by environment

inputs:
  cwd:
    description: Relative path to use for searching. Defaults to repo root. Will search upwards for config_file.
    required: true
    default: .
  config_file:
    description: Which file that contains the project config. Defaults to "projects.config.json".
    required: true
    default: projects.config.json
  required:
    description: Whether action should fail if no config file is found.
    required: false
    default: 'false'

runs:
  using: node20
  main: ./index.js

outputs:
  project_ids_by_environment:
    description: Project IDs by environment (as stringified JSON)
  project_numbers_by_environment:
    description: Project numbers by environment (as stringified JSON)
  environments:
    description: List of environments (as stringified JSON)
  matrix:
    description: Matrix of environments with project IDs and numbers. Use `matrix.environment` for environment, `matrix.project_id` for project ID, and `matrix.project_number` for project number.
  has_matrix:
    description: Whether the matrix is empty or not; `true` if there are more than zero results, `false` otherwise.