name: Replace Terraform variables with secrets
description: Replace Terraform variables with secrets

inputs:
  secrets_json:
    description: JSON string containing secrets to use for Terraform.
    required: true
  terraform_dir:
    description: The working directory, e.g. where the Terraform files are located.
    required: true
  secrets_file:
    description: The path to the Terraform tvars secrets file.
    required: true
    default: secrets.auto.tfvars

runs:
  using: node20
  main: ./index.js