name: Apply Terraform plan from artifact
description: Apply Terraform plan from artifact in previous job

inputs:
  terraform_dir:
    description: The working directory, e.g. where the Terraform files are located.
    required: true
  ref:
    description: Which commit, tag or branch to plan terraform from. Defaults to same as workflow is run from if empty.
    required: false
    default: ${{ github.sha }}
  workload_identity_project_id:
    description: The project ID of the workload identity project to use with `gcloud`. Will be used to set the `terraform@<workload_identity_project_id>.iam.gserviceaccount.com` service account.
    required: false
  workload_identity_project_number:
    description: The project number of the workload identity project to use with `gcloud`. Will be used to set workload identity provider to `projects/<workload_identity_project_number>/locations/global/workloadIdentityPools/default/providers/github`.
    required: false
  service_account_key:
    description: Service account key for the Terraform service account. Use either this or Workload Identity Federation.
    required: false
  github_token:
    description: Token used when authenticating with GitHub. Defaults to `github.token`.
    required: false
    default: ${{ github.token }}
  plan_artifact_name:
    description: Name of the plan file to download from GitHub artifacts. Defaults to "terraform.plan".
    required: false
    default: terraform.plan
  tf_backend_config:
    description: Terraform backend configuration to use. See https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration.
    required: false

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github_token }}

    - name: Read TF and TG versions
      working-directory: .
      shell: bash
      run: |
        echo "TF_VERSION=$(cat .terraform-version | awk '{$1=$1};1')" >> $GITHUB_ENV
        echo "TG_VERSION=$(cat .terragrunt-version | awk '{$1=$1};1')" >> $GITHUB_ENV

    - name: Setup Google Cloud SDK with service account key
      if: ${{ inputs.service_account_key }}
      uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v3.13.0
      with:
        service_account_key: ${{ inputs.service_account_key }}

    - name: Setup Google Cloud SDK with Workload Identity Federation
      if: ${{ !inputs.service_account_key }}
      uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v3.12.2
      with:
        project_id: ${{ inputs.workload_identity_project_id }}
        project_number: ${{ inputs.workload_identity_project_number }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@25ff9d20b92812c1870be23cce4b965c1ea59008
      with:
        terragrunt_version: ${{ env.TG_VERSION }}

    - name: Terragrunt init
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      run: test -z "${{ inputs.tf_backend_config }}" && terragrunt init -reconfigure || terragrunt init -reconfigure -backend-config=${{ inputs.tf_backend_config }}

    - name: Download plan
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.plan_artifact_name }}
        path: ${{ inputs.terraform_dir }}

    - name: Terragrunt apply
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: terragrunt apply -input=false -no-color -auto-approve ${{ inputs.plan_artifact_name }}
      