name: Find Gradle module changes
description: Find changes in Gradle root modules, defined as a folder with `gradlew` present.
runs:
  using: node16
  main: ./index.js
inputs:
  token:
    description: GitHub token. Defaults to `github.token`.
    required: true
    default: ${{ github.token }}
  include_all:
    description: Whether to list all modules, or only changed modules. Defaults to `false`.
    required: true
    default: false
  ignore_modules:
    description: Comma-separated list of relative paths to ignore. Must include dot at start of relative path, e.g. `., ./system/alpha`.
  ignore_modules_regex:
    description: Regex of modules to ignore, e.g. 'utils/.*'.
  cwd:
    description: Relative path to use for searching and as root for `matrix.path` outputs. Defaults to repo root.
    required: true
    default: .
outputs:
  matrix:
    description: Matrix of Gradle modules with changes in this PR/push. Use `matrix.path` for full path, `matrix.segments` for an array of each path segment, or `matrix.folder` for the single folder containing the module.
  has_results:
    description: Whether the matrix is empty or not; `true` if there are more than zero results, `false` otherwise.