name: Read Integration testing config
description: Finds integration testing settings
runs:
  using: 'node12'
  main: './index.js'
inputs:
  cwd:
    description: Relative path to use for searching and as root for `matrix.path` outputs. Defaults to repo root.
    required: true
    default: .
outputs:
  environment:
    description: Environment name
  workload_identity_project_id:
    description: Project ID for the workload identity federation authentication
  workload_identity_project_number:
    description: Project number for the workload identity federation authentication
