name: Post PR to card
description: Uses a http POST to add PR to Kanbanize Card
runs:
  using: node16
  main: ./index.js
inputs:
  token:
    description: GitHub token. Defaults to `github.token`.
    required: true
    default: ${{ github.token }}
  apikey:
    description: API key to Kanbanize.
    required: true
  cardIdRegex:
    description: Regular expresion for obtaining cardId from pull request description.
    default: '(KB|KBi)-[0-9]+'
  kanbanizeSubdomain:
    description: Subdomain used for Kanbanize
    required: true
    default: 'norwegianpublicroadsadmin'
