name: Bump semver tag
description: Reads the latest tag, increments the version if a \#major, \#minor or \#patch tag is found in any commit msg in push, and creates a new tag.

runs:
  using: node12
  main: ./index.js
  
inputs:
  token:
    description: GitHub token. Defaults to `github.token`.
    required: true
    default: ${{ github.token }}

outputs:
  tag:
    description: The new tag, or empty string if no tag was created.