name: Set GitHub token from GitHub App
description: Creates a GitHub token for the GitHub App and sets it as GITHUB_TOKEN, as well as configures git to add it to all github.com HTTP calls.

inputs:
  private_key:
    description: Private key for the GitHub App
    required: true
  app_id:
    description: GitHub App ID
    required: true

runs:
  using: composite
  steps:
    - name: Get app token
      id: get_token
      uses: svvsaga/github-app-token@main
      with:
        private_key: ${{ inputs.private_key }}
        app_id: ${{ inputs.app_id }}

    - name: Set GitHub token
      working-directory: .
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ steps.get_token.outputs.token }}@github.com".insteadOf https://github.com
        echo "GITHUB_TOKEN=${{ steps.get_token.outputs.token }}" >> $GITHUB_ENV

outputs:
  token:
    description: GitHub token
    value: ${{ steps.get_token.outputs.token }}