name: Setup GCloud
description: Setup GCloud SDK. If service account key is passed, it will be used, otherwise the action looks for a `projects.config.json` file in the app root, and uses the project ID and number for the given environment to set up Workload Identity Federation. To generate a `projects.config.json`, see `npx generate-gcp-project-config` from https://github.com/svvsaga/node-modules-public.

inputs:
  service_account_key:
    description: The service account JSON secret key to use with `gcloud`. Either this or `app_root` and `environment` must be set.
    required: false
  app_root:
    description: The root directory to use for searching for `projects.config.json`.
    required: false
  environment:
    description: The environment to use for finding the project ID and number. Typically "STM", "ATM", "PROD" or "SHARED".
    required: false
  service_account:
    description: The service account to use with Workload Identity Federation. Defaults to `terraform`. Not used if `service_account_key` is set.
    required: false
    default: terraform

runs:
  using: composite
  steps:
    - name: Verify that the code has been checked out
      working-directory: .
      shell: bash
      run: |
        if [ ! -d .git ]; then
          echo "ERROR: Code must be checked out first"
          exit 1
        fi

    - name: Check inputs
      working-directory: .
      shell: bash
      run: |
        if [[ -z "${{ inputs.service_account_key }}" ]] && [[ -z "${{ inputs.app_root }}" || -z "${{ inputs.environment }}" ]]; then
          echo "ERROR: Either service_account_key must be set, or both app_root and environment"
          exit 1
        fi

    - name: Setup Google Cloud SDK with service account key
      id: setup_gcloud_with_service_account_key
      if: ${{ inputs.service_account_key }}
      uses: svvsaga/github-actions-public/setup-gcloud-with-json-key@v17.2.3
      with:
        service_account_key: ${{ inputs.service_account_key }}

    - name: Setup Google Cloud SDK with workload identity federation
      id: setup_gcloud_with_workload_identity
      if: ${{ !inputs.service_account_key }}
      uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v17.2.3
      with:
        app_root: ${{ inputs.app_root }}
        environment: ${{ inputs.environment }}
        service_account: ${{ inputs.service_account }}

outputs:
  credentials_file_path:
    description: The path to the credentials file used by `gcloud`.
    value: ${{ steps.setup_gcloud_with_service_account_key.outputs.credentials_file_path || steps.setup_gcloud_with_workload_identity.outputs.credentials_file_path }}
  access_token:
    description: The access token used with `gcloud` if WIF is used.
    value: ${{ steps.setup_gcloud_with_workload_identity.outputs.access_token }}