name: Apply Terraform plan
description: Apply Terraform plan

inputs:
  terraform_dir:
    description: The working directory, e.g. where the Terraform files are located.
    required: true
  ref:
    description: Which commit, tag or branch to plan terraform from. Defaults to same as workflow is run from if empty.
    required: false
    default: ${{ github.sha }}
  service_account_key:
    description: Terraform Service Account private key to use with `gcloud`.
    required: true
  github_token:
    description: Token used when authenticating with GitHub. Defaults to `github.token`.
    required: false
    default: ${{ github.token }}
  plan_artifact_name:
    description: Name of the plan file to download from GitHub artifacts. Defaults to "terraform.plan".
    required: false
    default: terraform.plan

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
  
    - name: Read TF and TG versions
      working-directory: .
      run: |
        echo "TF_VERSION=$(cat .terraform-version | awk '{$1=$1};1')" >> $GITHUB_ENV
        echo "TG_VERSION=$(cat .terragrunt-version | awk '{$1=$1};1')" >> $GITHUB_ENV

    - name: Setup Google Cloud SDK with Terraform service account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        service_account_key: ${{ inputs.service_account_key }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@25ff9d20b92812c1870be23cce4b965c1ea59008
      with:
        terragrunt_version: ${{ env.TG_VERSION }}

    - name: Terragrunt init
      run: terragrunt init

    - name: Download plan
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.plan_artifact_name }}
        path: ${{ inputs.terraform_dir }}

    - name: Terragrunt apply
      run: terragrunt apply -input=false -no-color -auto-approve sandbox.plan