name: Build and upload Gradle module

on:
  workflow_call:
    inputs:
      storage_bucket:
        description: The GCP storage bucket into which to upload artifact
        type: string
        required: true
      saga_app_root:
        description: Path to source code project from root of Git repo
        type: string
        required: true
      destination_path:
        description: Path within storage bucket where to upload artifact. Defaults to `saga_app_root`.
        type: string
        required: false
        default: ""
      version_property:
        description: Project property used to set app version
        required: false
        type: string
        default: appVersion
      app_version:
        description: Will set the app version of the JAR to be built and published
        required: false
        type: string
        default: ${{ github.run_number }}
      ref:
        description: Which ref to create release for. Defaults to same as workflow is run from if empty.
        required: false
        type: string
        default: ${{ github.sha }}
      workload_identity_project_id:
        description: The project ID of the workload identity project to use with `gcloud`.
        type: string
        required: false
        default: ""
      workload_identity_project_number:
        description: The project number of the workload identity project to use with `gcloud`.
        type: string
        required: false
        default: ""
      workload_identity_service_account:
        description: The username of the service account to use with `gcloud` (before the @). Will be used with the workload_identity_project_id. Defaults to `publisher`.
        type: string
        required: false
        default: publisher
    secrets:
      storage_bucket_sa_publisher_key:
        description: Key for service account that has permission to upload to the given GCP storage bucket
        required: false


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REF: ${{ github.inputs.ref }}

jobs:
  build_module:
    name: Build module and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.saga_app_root }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build function
        run: ../gradlew shadowJar -P${{ inputs.version_property }}=${{ inputs.app_version }}

      - name: Zip jars
        run: find . -type f -name "*.jar" -exec bash -c 'zip -j `basename {}`.zip {}' \;

      - name: Setup Google Cloud SDK with service account key
        uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v3.13.0
        if: ${{ secrets.storage_bucket_sa_publisher_key != '' }}
        with:
          service_account_key: ${{ secrets.storage_bucket_sa_publisher_key }}

      - name: Setup Google Cloud SDK with Workload Identity Federation
        uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v3.13.0
        if: ${{ secrets.storage_bucket_sa_publisher_key == '' }}
        with:
          project_id: ${{ inputs.workload_identity_project_id }}
          project_number: ${{ inputs.workload_identity_project_number }}
          service_account: ${{ inputs.workload_identity_service_account }}

      - name: Publish to GCS
        uses: google-github-actions/upload-cloud-storage@v0.5.0
        with:
          path: ${{ inputs.saga_app_root }}
          destination: ${{ inputs.storage_bucket }}/${{ inputs.destination_path || inputs.saga_app_root }}
          glob: "*.zip"
          parent: false