name: Generate docs

on:
  push:
    branches:
      - main
    paths:
      - "**/action.yml"
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub token
        uses: svvsaga/github-actions-public/set-github-app-token@main
        id: set-token
        with:
          private_key: ${{ secrets.PUBLIC_ACTIONS_APP_PEM }}
          app_id: ${{ secrets.PUBLIC_ACTIONS_APP_ID }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.set-token.outputs.token }}

      - name: Generate docs
        run: for file in **/action.yml; do pushd $(dirname "$file") && npx action-docs --no-banner > README.md && popd; done

      - name: Update root README
        run: ./.github/scripts/md_file_tree.py README.md

      - name: Commit and push
        uses: svvsaga/add-and-commit
        with:
          message: Update action docs