name: Publish new version
on:
  push:
    branches:
      - master
    paths:
      - "**/*.ts"

jobs:
  publish-new-version:
    name: Publish new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Find severity of push
        uses: ../../find-severity-of-push
        id: find-severity
      
      - name: Publish new version
        run: npm run publish:${{ steps.find-severity.output.severity }} && git push origin master --follow-tags